<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>KRocketDocumentScanner.App.ViewModels</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="KRocketDocumentScanner.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../KRocketDocumentScanner.Core/KRocketDocumentScanner.Core.csproj" />
  </ItemGroup>

</Project>
